[Settings]
  ID = "ees4760"

[[redirects]]
  from = "https://www.ees4760.jgilligan.org/*"
  to   = "https://ees4760.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://www.ees4760.jgilligan.org/*"
  to   = "https://ees4760.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://ees4760.netlify.com/*"
  to   = "https://ees4760.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://ees4760.netlify.com/*"
  to   = "https://ees4760.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/static/*"
  to = "https://static.jgilligan.org/ees4760/:splat"
  status = 200

[[redirects]]
  from = "/analyze_behaviorspace/*"
  to = "https://shiny.jgilligan.org/ees-4760/analyze-behaviorspace/:splat"
  status = 302

[[redirects]]
  from = "/analyze-behaviorspace/*"
  to = "https://shiny.jgilligan.org/ees-4760/analyze-behaviorspace/:splat"
  status = 302

[[redirects]]
  from = "/contour/*"
  to = "https://shiny.jgilligan.org/ees-4760/contour/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
