---
title: Introduction to NetLogo
class_date: '2018-01-16'
class_number: 3
weight: 3
slug: reading_03
pubdate: '2018-01-01'
date: '2018-01-16'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Homework

Homework #2 is due today: Mushroom hunt. See the homework assignment sheet for details.

## Reading:

* Railsback & Grimm, Ch. 2.

### Reading Notes:

Familiarize yourself with NetLogo. I recommend that you read through the chapter with NetLogo open on your computer. Feel free to play around with NetLogo and try things out. The homework consists of following the step-by-step creation of a model in section 2.3.

**Errata for chapter 2:**

* On page 20, after you add the `setup` and `go` buttons to the interface, but before you write the `go` procedure, when you click the "Check" button, it will take you to the interface page because the `go` button has an eror: the procedure `go` does not exist yet. 
  After you write the `go` procedure in the Code tab, then the Check button will work as described in the book.
* The first bullet on page 21 should read:
   * Just as we created the `setup` procedure (with two lines saying `to setup` and `end`, write the "skeleton" of the `go` procedure.
