---
title: Introducing NetLogo
subtitle: '`r params$par_subtitle`'
due_date: '`r params$par_date`'
assignment_type: Homework
short_assignment_type: HW
med_assignment_type: Homework
assignment_number: 2
weight: 2
slug: homework_02
pubdate: '2026-07-31'
date: '`r params$par_date`'
params:
  par_date: '2026-09-02'
  par_subtitle: ~
pdf_url: /files/homework_asgts/homework_02.pdf
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
---
## Homework

### Homework Exercises:



* As you read along with Section 2.3, follow along on your computer and build the _Mushroom Hunt_ model by typing in the code shown in the textbook. The whole program is shown on pages 27--29.
  **Save your model as `mushroom_hunt.nlogox`**.

  This exercise may seem very simple, but it is the first step toward learning how to program NetLogo and it will be an important first step toward writing your own models.

  After you are done typing in your model, try running it.

  **When you are done, turn your model in on Brightspace.**

### Notes on Homework:


This, and future homework assignments will be due on Brightspace on the due-date before midnight (if it's assigned for Wednesday, then before Wednesday turns to Thursday, Nashville time). 
I am not super-strict about this and will not penalize you if you upload your assignment a little bit after the deadline ("a little bit" means minutes, not hours or days).

I recommend getting together with a classmate and working together on this assignment. Since the assignment consists of typing code in and running it, do not worry about your work being identical to your partner's. 
However, I strongly recommend that you type everything in yourself because you will not learn if you just copy someone else's code or download the code from a source on the web.

If you run into trouble and cannot make your model work, do not worry. Ask a classmate for help, or email me (and attach your `.nlogox` model file), or simply come to class with questions about the problems you had getting your model to work.