---
title: Experimenting with NetLogo
subtitle: '`r params$par_subtitle`'
due_date: '`r params$par_date`'
assignment_type: Homework
short_assignment_type: HW
med_assignment_type: Homework
assignment_number: 4
weight: 4
slug: homework_04
pubdate: '2026-07-31'
date: '`r params$par_date`'
params:
  par_date: '2026-09-09'
  par_subtitle: ~
pdf_url: /files/homework_asgts/homework_04.pdf
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
---
## Homework

### Preliminary Information

Upload your work to Brightspace when you're done (Word or text files for the descriptions and ODD document, and `.nlogox` files for your NetLogo models).

When there is more than one file for a homework assignment, you can either upload all the different files, or upload a Zip file containing the files for the different parts of the assignment. 
Give your files informative names. When a homework assignment has more than one problem, give the file or files for each problem a name that starts with the problem (e.g., `ex_2_3_model.nlogox` and `ex_2_3_answer.docx` for exercise 2.3). 
Exercise 2.4 calls for you to create 7 different model files (each one is a variation on the mushroom hunt), so you might call them `ex_2_4_a_model.nlogox`, `ex_2_4_b_model.nlogox`, ..., `ex_2_4_g_model.nlogox`.

Some problems in this homework set call for you to write a NetLogo model and also answer questions about the model. For answering the questions, you may take any of these approaches:

1. Edit the INFO page for your NetLogo model and add the following (this example is for exercise 2.3)
   ```
   # Exercise 2.3

   When I ran the model ...
   ```

2. Write your answer in a Word file or other document file (text, PDF, etc.) and put the homework answers there. You can either make a separate document for each exercise 
   (e.g., answers for exercise 2.3 go in `ex_2_3.docx`, answers for exercise 3.3 go in `ex_3_3.docx`), or you can make a single document file (e.g., with the 
   title like `homework_4_answers.docx` or something similar) and put the homework answers in there, as follows:

   > * **Exercise 2.3:** When I ran the model ...
   > * **Exercise 3.3:** This is how I would use a model to answer questions about the spread of COVID-19 ...

3. If your answers include diagrams or other kinds of figures or illustrations that are a pain to do in Word, you can hand-write your answers (**legibly!**), take a photo of them, and upload the photo (`.jpg`, `.png`, or `.webp` format, please!).

### Homework Exercises:



* Railsback & Grimm, Chapter 2, exercises Exercises 2.3--2.4.

  For exercise 4 in chapter 2, you will make seven sequential modifications of the basic mushroom hunt model. Each step modifies the previous one, so the last model will have all the modifications from the bulleted list in Ex. 2.4.
  Save each model with a new name, such as `ex_2_4a.nlogox`, `ex_2_4b.nlogox`, \dots, `ex_2_4g.nlogox`

* Railsback & Grimm, Chapter 3 exercise 3.3.

  Write your answers in any convenient text format (a simple text file, a Word document, a `.pdf` file, or whatever suits you). Call the file `ex_3_3.docx` (or `ex_3_3.pdf`, etc.).

### Notes on Homework:


My advice for Chapter 3, Exercise 3 is don't be too ambitious with your model, but keep it very
simple. Don't worry about getting everything right. If there are things you don't feel sure about or
don't know how to express, you should just write a parenthetical note in your ODD document commenting
on your difficulty. Come to class prepared to talk about how this exercise went and where
you felt confused about trying to specify your model.