---
title: Reproducing a model from its ODD
subtitle: '`r params$par_subtitle`'
due_date: '`r params$par_date`'
assignment_type: Homework
short_assignment_type: HW
med_assignment_type: Homework
assignment_number: 6
weight: 6
slug: homework_06
pubdate: '2025-07-31'
date: '`r params$par_date`'
params:
  par_date: '2025-09-17'
  par_subtitle: ~
pdf_url: /files/homework_asgts/homework_06.pdf
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
---
## Homework

### Homework Exercises:

* **Graduate Students:**



  * Graduate students should do Railsback & Grimm, Ex. 5.11

### Notes on Homework:



* **Graduate Students:** You can download the journal article for this exercise, [R. Jovani & V. Grimm. (2008) "Breeding synchrony in colonial birds: From local stress to global harmony", _Proc. Royal Soc. London B_ **275**, 1567--63](/files/models/chapter_05/Jovani_Grimm_2008_Breeding.pdf) from the class web site,
  <https://ees4760.jgilligan.org/files/models/chapter_05/Jovani_Grimm_2008_Breeding.pdf>.

  You don't have to reproduce all of the figures in the paper. Focus on reproducing the information in Figure 2 (make a figure of colony synchrony versus NR and some other figures showing histograms of breeding dates for NR = 0.00, 0.08, 0.20, and 1.00 and comparing them to the histograms in Fig. 2.

  You may also (optionally) try to reproduce Fig. 1 and Fig. 4.

  Fig. 3 is very hard to reproduce because you would need to write a reporter to calculate the size of the colonies and that is quite difficult with what you know at this point about NetLogo programming, so I don't recommend this.

  * The paper by Jovani and Grimm forgot to specify the parameter `SD.` It should have the value 10.0.

