---
title: Research project report
subtitle: '`r params$par_subtitle`'
due_date: '`r params$par_date`'
assignment_type: Project
short_assignment_type: PRJ
assignment_number: 18
weight: 18
slug: project_report
pubdate: '2025-07-31'
date: '`r params$par_date`'
params:
  par_date: '2025-12-06'
  par_subtitle: ~
pdf_url: /files/homework_asgts/project_report.pdf
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
---
## Homework

### Homework Exercises:



* Turn in a written report about your research project. Your report should follow the model of a research report for _Science_ magazine:

### Notes on Homework:


Your report should have the following structure:

#. Abstract (1 paragraph summary of the paper, focusing on highlights)
#. Introduction
   * Research question and why it’s interesting
#. Methods
   * Describe the model you started with and how you changed it to answer your research question
   * Describe the experiments you ran with the model.
   * Describe what outputs you measured
#. Results
   * What did you see (graphs of output, pictures of turtles on patches, etc.)
#. Discussion, conclusions:
   * What did you learn from the results of your experiment?
   * If you had more time, what would you do next with your model?
   * Do you think these results point to possible uses for your model?
#. References

**See the [assignment](/assignment/ResearchProjectAssignment.pdf) for further details.**